=begin
#NIUM Platform

#NIUM Platform

The version of the OpenAPI document: 2023.12.12
Contact: experience@nium.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NiumClient::BeneficiaryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BeneficiaryApi' do
  before do
    # run before each test
    @api_instance = NiumClient::BeneficiaryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BeneficiaryApi' do
    it 'should create an instance of BeneficiaryApi' do
      expect(@api_instance).to be_instance_of(NiumClient::BeneficiaryApi)
    end
  end

  # unit tests for account_verification
  # Account verification (Confirmation of Payee)
  # This API allows you to verify a beneficiary account details. &gt; &gt; ℹ️ INFO   &gt;This API only supports account verification for certain destination corridors. &gt;Refer to the   [Account verification user guide](/apis/docs/account-verification#supported-corridors-for-account-verification) for details.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param account_validation_request_dto accountValidationRequestDTO
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value.
  # @return [AccountValidationResponseDTO]
  describe 'account_verification test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for add_beneficiary
  # Add Beneficiary
  # This API allows you to add a beneficiary to transfer funds.  &gt;⚠️ WARNING   &gt;This API version is deprecated. Eventually, a deprecated API version becomes unsupported. [Add Beneficiary V2](/apis/reference/addbeneficiaryv2) is the latest version of this API.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param add_beneficiary_request addBeneficiaryRequest
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [Resource]
  describe 'add_beneficiary test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for add_beneficiary_v2
  # Add Beneficiary V2
  # This API allows you to add a beneficiary to transfer funds.   &gt; ⚠️ IMPORTANT    Some fields are conditional based on corridors. Use the [Beneficiary Validation Schema V2](/apis/reference/beneficiaryvalidationschemav2) with the currency code and payout method to determine if a field is required or not.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param add_beneficiary_request_dto addBeneficiaryRequestDTO
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [BeneficiaryResponseDTO]
  describe 'add_beneficiary_v2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for beneficiary_details
  # Beneficiary Details
  # This API allows you to fetch beneficiary details of an individual beneficiary.  &gt;⚠️ WARNING   &gt;This API version is deprecated. Eventually, a deprecated API version becomes unsupported. [Beneficiary Details V2](/apis/reference/beneficiarydetailsv2) is the latest version of this API.
  # @param beneficiary_hash_id Unique beneficiary hash ID.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [Resource]
  describe 'beneficiary_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for beneficiary_details_v2
  # Beneficiary Details V2
  # This API allows you to fetch beneficiary details of an individual beneficiary.
  # @param beneficiary_hash_id Unique beneficiary hash ID.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [BeneficiaryResponseDTO]
  describe 'beneficiary_details_v2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for beneficiary_list
  # Beneficiary List
  # This API allows you to fetch beneficiary details.  &gt;⚠️ WARNING   &gt;This API version is deprecated. Eventually, a deprecated API version becomes unsupported. [Beneficiary List V2](/apis/reference/beneficiarylistv2) is the latest version of this API.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<Hash<String, String>>] :parameters parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [Resource]
  describe 'beneficiary_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for beneficiary_list_v2
  # Beneficiary List V2
  # This API allows you to fetch beneficiary details.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<Hash<String, String>>] :parameters parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [Array<BeneficiaryResponseDTO>]
  describe 'beneficiary_list_v2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for beneficiary_validation_schema
  # Beneficiary Validation Schema
  # This API will allow you to fetch the validation schema for beneficiary validation details.  &gt;⚠️ WARNING   &gt;This API version is deprecated. Eventually, a deprecated API version becomes unsupported. [Beneficiary Validation Schema V2](/apis/reference/beneficiaryvalidationschemav2) is the latest version of this API.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param currency_code This field accepts the 3-letter [ISO-4217 currency code](doc:currency-and-country-codes).
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :payout_method This field can accept the different modes of payout.This field can accept one of the following values: 1.LOCAL 2.SWIFT 3.WALLET Default value of the parameter is LOCAL.
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [Resource]
  describe 'beneficiary_validation_schema test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for beneficiary_validation_schema_v2
  # Beneficiary Validation Schema V2
  # This API will allow you to fetch the validation schema for beneficiary validation details.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param currency_code This field accepts the 3-letter [ISO-4217 currency code](doc:currency-and-country-codes).
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :payout_method This field can accept the different modes of payout.
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [String]
  describe 'beneficiary_validation_schema_v2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for confirmationof_payee
  # Confirmation of Payee (Previous version)
  # This API allows you to Validate Beneficiary Details.  &gt;ℹ️ INFO   &gt;This API only supports account verification for below destination corridors. &gt;**For LOCAL payment method:** Vietnam (VN), Thailand (TH), India (IN), Pakistan(PK), Malaysia(MY), Indonesia (ID) &gt;**For PROXY payment method:** Singapore (SG), India (IN), Malaysia(MY)
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param beneficiary_validation_request_dto beneficiaryValidationRequestDTO
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [BeneficiaryValidationResponseDTO]
  describe 'confirmationof_payee test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_beneficiary
  # Delete Beneficiary
  # This API allows you to delete a beneficiary.
  # @param beneficiary_hash_id Unique beneficiary hash ID.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [Resource]
  describe 'delete_beneficiary test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_beneficiary
  # Update Beneficiary
  # This API allows you to update beneficiary details.
  # @param beneficiary_hash_id Unique beneficiary hash ID.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @option opts [AddBeneficiaryRequest] :add_beneficiary_request Info:  Update Beneficiary API will be restricted when a remittance transaction for the beneficiary is Pending.
  # @return [Resource]
  describe 'update_beneficiary test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_beneficiary_v2
  # Update Beneficiary V2
  # This API allows you to update beneficiary details.
  # @param beneficiary_hash_id Unique beneficiary hash ID.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @option opts [UpdateBeneficiaryRequestDTO] :update_beneficiary_request_dto Info:  Update Beneficiary API will be restricted when a remittance transaction for the beneficiary is Pending.
  # @return [BeneficiaryResponseDTO]
  describe 'update_beneficiary_v2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
