=begin
#NIUM Platform

#NIUM Platform

The version of the OpenAPI document: 2023.12.12
Contact: experience@nium.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NiumClient::CardsReferenceDataApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CardsReferenceDataApi' do
  before do
    # run before each test
    @api_instance = NiumClient::CardsReferenceDataApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CardsReferenceDataApi' do
    it 'should create an instance of CardsReferenceDataApi' do
      expect(@api_instance).to be_instance_of(NiumClient::CardsReferenceDataApi)
    end
  end

  # unit tests for reference_exchange_rate
  # Reference Exchange Rate
  # This API allows you to get the reference exchange rate.
  # @param card_scheme This field accepts the card scheme provider name: Visa Mastercard
  # @param client_hash_id Unique customer identifier generated on customer creation.
  # @param from_amount From Amount also known as transaction amount that will be converted from the fromCurrency and to the toCurrency.
  # @param from_currency This field contains the 3-letter [ISO-4217 currency code](doc:currency-and-country-codes) of the transaction currency. Should be one of the applicable EEA currencies (EUR, BGN, HRK, CZK, DKK, HUF, PLN, RON, SEK, GBP, ISK, CHF and NOK).
  # @param to_currency This field contains the 3-letter [ISO-4217 currency code](doc:currency-and-country-codes) of the cardholder billing currency. Should be one of the applicable EEA currencies (EUR, BGN, HRK, CZK, DKK, HUF, PLN, RON, SEK, GBP, ISK, CHF and NOK)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value.
  # @return [ReferenceRateResponseDto]
  describe 'reference_exchange_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
