=begin
#NIUM Platform

#NIUM Platform

The version of the OpenAPI document: 2023.12.12
Contact: experience@nium.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NiumClient::CustomerWalletBalanceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomerWalletBalanceApi' do
  before do
    # run before each test
    @api_instance = NiumClient::CustomerWalletBalanceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerWalletBalanceApi' do
    it 'should create an instance of CustomerWalletBalanceApi' do
      expect(@api_instance).to be_instance_of(NiumClient::CustomerWalletBalanceApi)
    end
  end

  # unit tests for wallet_balance
  # Wallet Balance
  # This API allows you to fetch balance for a specific wallet.
  # @param client_hash_id Unique client identifier generated and shared before API handshake.
  # @param customer_hash_id Unique customer identifier generated on customer creation.
  # @param wallet_hash_id Unique wallet identifier generated simultaneously with customer creation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [Array<WalletBalanceResponseDTO>]
  describe 'wallet_balance test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
