=begin
#NIUM Platform

#NIUM Platform

The version of the OpenAPI document: 2023.12.12
Contact: experience@nium.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NiumClient::RatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RatesApi' do
  before do
    # run before each test
    @api_instance = NiumClient::RatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RatesApi' do
    it 'should create an instance of RatesApi' do
      expect(@api_instance).to be_instance_of(NiumClient::RatesApi)
    end
  end

  # unit tests for aggregated_exchange_rates
  # Fetch historic aggregated exchange rates
  # This API will retrieve aggregated time series of historical exchange rate.
  # @param source_currency_code This field contains the 3-letter [currency-and-country-codes](https://docs.nium.com/apis/docs/currency-and-country-codes).
  # @param destination_currency_code This field contains the 3-letter [currency-and-country-codes](https://docs.nium.com/apis/docs/currency-and-country-codes).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization 
  # @option opts [String] :csrf_token 
  # @option opts [Time] :start The start timestamp used to filter the aggregated time series. Must be in the format &#39;yyyy-mm-ddTHH:MM:SSZ&#39;.
  # @option opts [Time] :_end The end timestamp used to filter the aggregated time series. Must be in the format &#39;yyyy-mm-ddTHH:MM:SSZ&#39;.
  # @option opts [Window] :window Specifies the field by which the results should be grouped.
  # @option opts [String] :x_request_id Enter a unique UUID value.
  # @return [ExchangeRatesGetResponse]
  describe 'aggregated_exchange_rates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for exchange_rate_v2
  # Exchange Rate V2
  # This API fetches the interbank FX rate for a currency pair. Note that the rate provided does not include the Nium markup.
  # @param source_currency_code This field contains the 3-letter [ISO-4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) for the source amount.
  # @param destination_currency_code This field contains the 3-letter [ISO-4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) for the destination amount.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_request_id Enter a unique UUID value
  # @return [ExchangeRateV2ResponseDto]
  describe 'exchange_rate_v2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
