=begin
#NIUM Platform

#NIUM Platform

The version of the OpenAPI document: 2023.12.12
Contact: experience@nium.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NiumClient::CardAssignResponseDTO
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NiumClient::CardAssignResponseDTO do
  let(:instance) { NiumClient::CardAssignResponseDTO.new }

  describe 'test an instance of CardAssignResponseDTO' do
    it 'should create an instance of CardAssignResponseDTO' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NiumClient::CardAssignResponseDTO)
    end
  end

  describe 'test attribute "card_hash_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "card_activation_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["VIRTUAL_ACTIVE,INACTIVE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.card_activation_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "masked_card_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
