=begin
#NIUM Platform

#NIUM Platform

The version of the OpenAPI document: 2023.12.12
Contact: experience@nium.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NiumClient::ConversionSchedule
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NiumClient::ConversionSchedule do
  let(:instance) { NiumClient::ConversionSchedule.new }

  describe 'test an instance of ConversionSchedule' do
    it 'should create an instance of ConversionSchedule' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NiumClient::ConversionSchedule)
    end
  end

end
