=begin
#NIUM Platform

#NIUM Platform

The version of the OpenAPI document: 2023.12.12
Contact: experience@nium.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NiumClient::CorporateDocumentDetailsDTO
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NiumClient::CorporateDocumentDetailsDTO do
  let(:instance) { NiumClient::CorporateDocumentDetailsDTO.new }

  describe 'test an instance of CorporateDocumentDetailsDTO' do
    it 'should create an instance of CorporateDocumentDetailsDTO' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NiumClient::CorporateDocumentDetailsDTO)
    end
  end

  describe 'test attribute "document_issuance_country"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "identification_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "identification_value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
