=begin
#NIUM Platform

#NIUM Platform

The version of the OpenAPI document: 2023.12.12
Contact: experience@nium.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NiumClient::TransactionsReceiptDTO
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NiumClient::TransactionsReceiptDTO do
  let(:instance) { NiumClient::TransactionsReceiptDTO.new }

  describe 'test an instance of TransactionsReceiptDTO' do
    it 'should create an instance of TransactionsReceiptDTO' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NiumClient::TransactionsReceiptDTO)
    end
  end

  describe 'test attribute "document"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "receipt_file_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "receipt_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["image/png", "image/jpg", "image/jpeg", "application/pdf"])
      # validator.allowable_values.each do |value|
      #   expect { instance.receipt_type = value }.not_to raise_error
      # end
    end
  end

end
