=begin
#NIUM Platform

#NIUM Platform

The version of the OpenAPI document: 2023.12.12
Contact: experience@nium.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module NiumClient
  class Payout
    # The audit Id must be taken from [Exchange Rate Lock and Hold](ref:exchangeratelockandhold) API.
    attr_accessor :audit_id

    # This field accepts the destination amount for remittance. Either the source or the destination amount is mandatory.  Allowed decimal limit is 2.
    attr_accessor :destination_amount

    # This field indicates if compliance checks are to be done at the time of payout creation. This field is applicable only for scheduled and Post-Funded payouts.
    attr_accessor :pre_screening

    # This field accepts scheduled payout date in yyyy-MM-dd format
    attr_accessor :scheduled_payout_date

    # This field should denote the date of providing of service/export in yyyy-MM-dd format
    attr_accessor :service_time

    # This field accepts the source amount for remittance. Either the source or the destination amount is mandatory.  Allowed decimal limit is 2.
    attr_accessor :source_amount

    # This field accepts the source currency for remittance.
    attr_accessor :source_currency

    # This field accepts the swift fee type and defines who will bear the SWIFT charges for the given transaction. Clients can send any of the below values basis which, they will be charged for the SWIFT transaction. In case this field is absent SHA will be applied by default.  SHA - SWIFT charges shared by the customer and beneficiary OUR - SWIFT charges borne by the customer  Note: Clients should make sure that fee template is configured for each of the swift fee type. To know if the template is configured, clients should call [Fee Details](/apis/reference/feedetails) API
    attr_accessor :swift_fee_type

    # This field should denote the invoice number relevant to the transaction
    attr_accessor :trade_order_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'audit_id' => :'audit_id',
        :'destination_amount' => :'destination_amount',
        :'pre_screening' => :'preScreening',
        :'scheduled_payout_date' => :'scheduledPayoutDate',
        :'service_time' => :'serviceTime',
        :'source_amount' => :'source_amount',
        :'source_currency' => :'source_currency',
        :'swift_fee_type' => :'swiftFeeType',
        :'trade_order_id' => :'tradeOrderID'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'audit_id' => :'Integer',
        :'destination_amount' => :'Float',
        :'pre_screening' => :'Boolean',
        :'scheduled_payout_date' => :'String',
        :'service_time' => :'String',
        :'source_amount' => :'Float',
        :'source_currency' => :'String',
        :'swift_fee_type' => :'String',
        :'trade_order_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NiumClient::Payout` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NiumClient::Payout`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'audit_id')
        self.audit_id = attributes[:'audit_id']
      end

      if attributes.key?(:'destination_amount')
        self.destination_amount = attributes[:'destination_amount']
      end

      if attributes.key?(:'pre_screening')
        self.pre_screening = attributes[:'pre_screening']
      end

      if attributes.key?(:'scheduled_payout_date')
        self.scheduled_payout_date = attributes[:'scheduled_payout_date']
      end

      if attributes.key?(:'service_time')
        self.service_time = attributes[:'service_time']
      end

      if attributes.key?(:'source_amount')
        self.source_amount = attributes[:'source_amount']
      end

      if attributes.key?(:'source_currency')
        self.source_currency = attributes[:'source_currency']
      end

      if attributes.key?(:'swift_fee_type')
        self.swift_fee_type = attributes[:'swift_fee_type']
      end

      if attributes.key?(:'trade_order_id')
        self.trade_order_id = attributes[:'trade_order_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      swift_fee_type_validator = EnumAttributeValidator.new('String', ["BEN", "OUR", "SHA"])
      return false unless swift_fee_type_validator.valid?(@swift_fee_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] swift_fee_type Object to be assigned
    def swift_fee_type=(swift_fee_type)
      validator = EnumAttributeValidator.new('String', ["BEN", "OUR", "SHA"])
      unless validator.valid?(swift_fee_type)
        fail ArgumentError, "invalid value for \"swift_fee_type\", must be one of #{validator.allowable_values}."
      end
      @swift_fee_type = swift_fee_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          audit_id == o.audit_id &&
          destination_amount == o.destination_amount &&
          pre_screening == o.pre_screening &&
          scheduled_payout_date == o.scheduled_payout_date &&
          service_time == o.service_time &&
          source_amount == o.source_amount &&
          source_currency == o.source_currency &&
          swift_fee_type == o.swift_fee_type &&
          trade_order_id == o.trade_order_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [audit_id, destination_amount, pre_screening, scheduled_payout_date, service_time, source_amount, source_currency, swift_fee_type, trade_order_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = NiumClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
